from flask import Flask
from src.data import load_descriptions
from src.sommelier import AI_Sommelier
app = Flask(__name__)

DATA_DIR = './input'
descriptions = load_descriptions(DATA_DIR)
sommelier = AI_Sommelier(descriptions, subset=10_000)

@app.route('/')
def homepage():
	
    return f"""
    <h2>Human Sommelier</h2>
    <p>{sommelier.sample_review()}</p>
    <h2>AI Sommelier</h2>
    <p>{sommelier.write_review()}</p>
    <h5>~~~Refresh for new review~~~</h5>
    
    <img src="http://loremflickr.com/600/400/wine"/>
    <p>Generated by https://github.com/zwrankin/beer_and_wine_NLP<p>
	
    """

if __name__ == '__main__':
    app.run(debug=True, use_reloader=True)
